---
# ansible-playbook -i HOST, -e package=git package.yml
# ansible-playbook -i HOST, -e "p=['gcc','make']" package.yml
- hosts:
    all

  vars:
    package: ''
    packages: "{{p|default([])}}"

  tasks:

  - debug:
      var: packages

  - package:
      name: "{{package}}"
    when: package != ''

  - package:
      name: "{{item}}"
    with_items: "{{packages}}"
