---
# ansible-playbook -i HOST, -e package=git package.yml
# ansible-playbook -i HOST, -e "p=['gcc','make']" package.yml
-
  hosts:
    all

  vars:
    package: ''
    packages: "{{p|default([])}}"

  tasks:

  -
    name: package
    package:
      name: "{{package}}"
    when: package != ''

  -
    name: packages
    package:
      name: "{{item}}"
    with_items: "{{packages}}"
